% Run BP sorting

%% files
file = '/kyb/agmbrecordings/Dennis/2014-10-03_13-39-12/2014-10-03_13-39-19/Electrophysiology%d.h5';


%% fit model
br = baseReader(file, 's1c*');
ndx = strfind(file, '/');
temp = ['/kyb/agmbrecordings/tmp/' file(ndx(end - 3) : ndx(end - 1))];

bps = BPSorter('V1x32-Poly2', ...
    'TempDir', temp, ...
    'Debug', true, ...
    'Verbose', true, ...
    'MaxSamples', 5e6, ...
    'BlockSize', 5 * 60, ...
    'FullIter', 0, ...
    'pruningRadius', 55, ...
    'waveformBasis', getfield(load('B'), 'B'), ...
    'samples', -12 : 24, ...
    'logging', true, ...
    'mergeThreshold', 0.85, ...
    'pruningThreshold', 1.5, ...
    'driftRate', 0.005);
bps.readData(br);
[X, Uw, priors, temporal, spatial] = bps.fit();
save(fullfile(bps.TempDir, 'results'), 'bps', 'X', 'Uw', 'priors', 'temporal', 'spatial')
